package org.project.util.enums;

public enum HandlerName {
    MAIN_MENU,
    GET_FIRST_NAME,
    GET_GIT_INFO,
    TEAM_MENU,
    TEAM_MENU_NEXT,
    TEAM_DETAILS,
    TEAM_DETAILS_NEXT,
    TEAM_CREATION,
    TEAM_CONFIRMED,
    STUDENT_CREATION,
    STUDENT_CONFIRMED,
    STUDENT_REPOS,
    STUDENT_REPOS_NEXT,
    REPO_CREATION,
    REPO_DETAILS,
    COMMIT_DETAILS,
    BRANCH_DETAILS,
    LEAD_MENU,
    SEARCH_GIT
}
